In [55]:
import numpy as np

In [56]:
li=[1,2,3,4]

In [57]:
type(li)

list

In [59]:
x=np.array(li)

In [60]:
x

array([1, 2, 3, 4])

In [61]:
type(x)

numpy.ndarray

# Handling Missing Data

In [1]:
import pandas as pd
import numpy as np

In [2]:
data1=np.array([1, None,2,3])

In [3]:
data1

array([1, None, 2, 3], dtype=object)

In [4]:
%timeit np.arange(1E6, dtype=int).sum()

2.55 ms ± 333 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [5]:
%timeit np.arange(1E6, dtype=object).sum()

67.7 ms ± 5.92 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [7]:
# data1.sum()

# pandas does not use None in its numerical array

In [8]:
data2= np.array([1,np.nan,3,4])

In [9]:
data2

array([ 1., nan,  3.,  4.])

In [10]:
type(data2)

numpy.ndarray

In [13]:
# 1 + None

In [14]:
1 + np.nan

nan

In [15]:
1 * np.nan

nan

In [16]:
0 * np.nan

nan

# NaN and None in pandas

In [17]:
pd.Series([1,np.nan,2,None])

0    1.0
1    NaN
2    2.0
3    NaN
dtype: float64

In [18]:
x= pd.Series(range(2), dtype=int)

In [19]:
x

0    0
1    1
dtype: int32

In [20]:
x[0] = None

In [21]:
x

0    NaN
1    1.0
dtype: float64

In [22]:
# pandas automatically converts the None to NaN value

type class

1. floating ----- no change-------np.nan
2. object --------no change-------np.nan or None
3. integer -------cast to float64-----np.nan
4. boolean-------cast to object -----None or np.nan

In [24]:
y = pd.Series(range(5), dtype=object)

In [25]:
y

0    0
1    1
2    2
3    3
4    4
dtype: object

In [26]:
y[0] = None

In [27]:
y

0    None
1       1
2       2
3       3
4       4
dtype: object

# pandas nullable dtypes

In [28]:
pd.Series([1,np.nan,2,None,pd.NA], dtype='Int32')

0       1
1    <NA>
2       2
3    <NA>
4    <NA>
dtype: Int32

In [29]:
pd.Series([1,np.nan,2,None,pd.NA], dtype='Int64')

0       1
1    <NA>
2       2
3    <NA>
4    <NA>
dtype: Int64

In [32]:
pd.Series([1,np.nan,2,None,pd.NA], dtype=object)

0       1
1     NaN
2       2
3    None
4    <NA>
dtype: object

In [41]:
pd.Series([1,np.nan,2,None], dtype=float)

0    1.0
1    NaN
2    2.0
3    NaN
dtype: float64

# Operating on null values

### isnull

The isnull() method returns a DataFrame object where all the values are replaced with a Boolean value True for NULL values, and otherwise False.

In [42]:
data=pd.Series([1,np.nan,'hello',None])

In [43]:
data

0        1
1      NaN
2    hello
3     None
dtype: object

In [44]:
data.isnull()

0    False
1     True
2    False
3     True
dtype: bool

### notnull

The notnull() method returns a DataFrame object where all the values are replaced with a Boolean value True for NOT NULL values, and otherwise False.

In [45]:
data

0        1
1      NaN
2    hello
3     None
dtype: object

In [46]:
data.notnull()

0     True
1    False
2     True
3    False
dtype: bool

In [47]:
data[data.notnull()]

0        1
2    hello
dtype: object

### dropna

The dropna() method removes the rows that contains NULL values.

In [48]:
data=pd.Series([1,np.nan,'hello',None])

In [49]:
data

0        1
1      NaN
2    hello
3     None
dtype: object

In [50]:
data.dropna()

0        1
2    hello
dtype: object

In [51]:
data

0        1
1      NaN
2    hello
3     None
dtype: object

### fillna

The fillna() method replaces the NULL values with a specified value.

In [52]:
data=pd.Series([1,np.nan,'hello',None])

In [53]:
data

0        1
1      NaN
2    hello
3     None
dtype: object

In [54]:
data.fillna(0)

0        1
1        0
2    hello
3        0
dtype: object